services:
  mysql-db:
    image: mysql:8.0
    container_name: optica-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: optica_auth
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10

  postgres-db:
    image: postgres:16-alpine
    container_name: optica-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: optica_products
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 10

  auth-service:
    build: ./backend/auth-service
    container_name: optica-auth-service
    restart: unless-stopped
    environment:
      PORT: 4001
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/optica_auth?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      JWT_SECRET: optica-jwt-secret-cambia-en-produccion-12345-67890-abcdef
      JWT_EXPIRATION_MS: 7200000
    ports:
      - "4001:4001"
    depends_on:
      mysql-db:
        condition: service_healthy

  product-service:
    build: ./backend/product-service
    container_name: optica-product-service
    restart: unless-stopped
    environment:
      PORT: 4002
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/optica_products
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      JWT_SECRET: optica-jwt-secret-cambia-en-produccion-12345-67890-abcdef
    ports:
      - "4002:4002"
    depends_on:
      postgres-db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      args:
        VITE_AUTH_URL: http://localhost:4001
        VITE_PRODUCT_URL: http://localhost:4002
    container_name: optica-frontend
    restart: unless-stopped
    ports:
      - "5173:80"
    depends_on:
      - auth-service
      - product-service

volumes:
  mysql_data:
  postgres_data:
